### ISSUE TITLE
Relative paths not working (on windows)

### ISSUE THREAD

**Issue by tapnisu** [akumarujon/wall-rs#2]
Вай зис ис нот воркинг, вай ит сет блек ас май валлпапер ват ис вронг виз ер раст программ!!!!

![image](https://github.com/akumarujon/wall-rs/assets/57483029/d7c34fb3-7c59-4dc0-9014-433af2496bf4)

ВАААААЙ

**Comment by aelloc** [comment]
айм каррентли ворркинг он диз

**Comment by aelloc** [comment]
май скил ишшу, фиксед чек нав

**Comment by tapnisu** [comment]
![image](https://github.com/akumarujon/wall-rs/assets/57483029/0abfc29e-3ee8-4235-a933-e06a7f2becea)

нау ви нид ту манадж ит ту ворк виз релатив патхс

**Comment by tapnisu** [comment]
Fuck

**Comment by aelloc** [comment]
йес

**Comment by tapnisu** [comment]
Fuck windows

**Comment by aelloc** [comment]
stay tunned
