### ISSUE TITLE
Seperate repositories

### ISSUE THREAD

**Issue by orzklv** [akumarujon/wall-rs#4]
We need to create 2 seperate repos for assets and source code itself to avoid overweight repos.

- wall-rs: rust source code for compiling binary
- wall-content: releases contents as an archive

**Comment by aelloc** [comment]
src - current repo
mirror - https://github.com/akumarujon/wall-rs-mirror

**Comment by aelloc** [comment]
also, check this xD

![image](https://i.imgur.com/dxbtVsk.png)

**Comment by aelloc** [comment]
so, are we keeping the pics folder?

**Comment by orzklv** [comment]
Nope, we should definitely seperate... if you want me to keep contributing to this project for sure. I don't wanna deal with huge ass big git repo that's filled with assets.

Thanks in advance.

**Comment by aelloc** [comment]
I think I can close this issue now.
